/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 arco.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { BoxCollaider, CylinderCollaider } from "../Collaiders/collaiders";

const keeperZones = {
  left: {
    // position: [-1.6, 1.2, 0],
    position: [-1.6, 0.3, 0],
    // rotacion horizontal
    rotation: [0, 0, Math.PI / 2],
  },
};

export function Goal(props) {
  const { keeperZone } = props;
  const { nodes, materials } = useGLTF("./models/goal/goal.gltf");

  useEffect(() => {
    console.log(keeperZone);
  }, [keeperZone]);

  return (
    <group>
      <group {...props} dispose={null}>
        <BoxCollaider
          args={[0.9, 2, 0.4]}
          position={keeperZones[keeperZone]?.position}
          rotation={keeperZones[keeperZone]?.rotation}
          mass={1}
          type="Static"
        />
        <CylinderCollaider
          scale={[0.1, 0.1, 7.32]}
          args={[0.1, 0.1, 7.32]}
          position={[0, 2.9, 0.5]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <CylinderCollaider
          args={[0.1, 0.1, 3]}
          position={[-3.66, 1.6, 0.5]}
          // scale={[0.2, 2.44, 0.2]}
          rotation={[0, 0, 0]}
        />
        <CylinderCollaider
          args={[0.1, 0.1, 3]}
          position={[3.66, 1.6, 0.5]}
          // scale={[0.2, 2.44, 0.2]}
          rotation={[0, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/goal/goal.gltf");
