export const goal_keeper_positions = {
  penalty: {
    idle: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0, 0, 0],
      retation: [Math.PI / 2, 0, 0],
      animation: "idle",
    },
    left_down: {
      position: [0, 0, 0],
      collider_position: [-1.6, 0.3, 0],
      collider_rotation: [0, 0, Math.PI / 2],
      retation: [Math.PI / 2, 0, 0],
      animation: "left down",
    },
    left_up: {
      position: [0, 0, 0],
      collider_position: [-1.9, 1, 0.5],
      collider_rotation: [0, 0, Math.PI / 2],
      retation: [Math.PI / 2, 0, 0],
      animation: "left up",
    },
    right_down: {
      position: [0, 0, 0],
      collider_position: [1.6, 0.3, 0],
      collider_rotation: [0, 0, Math.PI / 2],
      retation: [Math.PI / 2, 0, 0],
      animation: "right down",
    },
    right_up: {
      position: [0, 0, 0],
      collider_position: [1.9, 1, 0.5],
      collider_rotation: [0, 0, Math.PI / 2],
      retation: [Math.PI / 2, 0, 0],
      animation: "right up",
    },
    center: {
      position: [0, 0, 0],
      collider_position: [-0.3, 1.4, 0.5],
      collider_rotation: [0, 0, 0],
      retation: [Math.PI / 2, 0, 0],
      animation: "center",
    },
  },
  direct_free_kick: {
    idle: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0.9, 2, 0.4],
      retation: [Math.PI / 2, 0, 0],
      animation: "idle",
    },
    left_down: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0.9, 2, 0.4],
      retation: [Math.PI / 2, 0, 0],
      animation: "left down",
    },
    left_up: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0.9, 2, 0.4],
      retation: [Math.PI / 2, 0, 0],
      animation: "left up",
    },
    right_down: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0.9, 2, 0.4],
      retation: [Math.PI / 2, 0, 0],
      animation: "right down",
    },
    right_up: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0.9, 2, 0.4],
      retation: [Math.PI / 2, 0, 0],
      animation: "right up",
    },
    center: {
      position: [0, 0, 0],
      collider_position: [0, 0, 0],
      collider_rotation: [0.9, 2, 0.4],
      retation: [Math.PI / 2, 0, 0],
      animation: "center",
    },
  },
};
