/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 stadium.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Stadium(props) {
  const { nodes, materials } = useGLTF("./models/stadium/stadium.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI]} scale={0.01}>
        <mesh geometry={nodes.feeld.geometry} material={materials.M_Field4} />
        <mesh geometry={nodes.gradas.geometry} material={materials.M_gradas} />
        <mesh
          geometry={nodes.sponsor.geometry}
          material={materials.M_Sponsor_Low2}
        />
        <mesh
          geometry={nodes.terrain.geometry}
          material={materials.M_terrain}
        />
        <mesh
          geometry={nodes.Mesh002.geometry}
          material={materials.M_Fishnet}
        />
        <mesh
          geometry={nodes.Mesh002_1.geometry}
          material={materials.M_Metal}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/stadium/stadium.gltf");
